services:
  auth-db:
    image: postgres:16-alpine
    env_file:
      - ./services/auth-service/db.env
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./services/auth-service/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-api:
    build: ./services/auth-service
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - auth-db
    ports:
      - "4001:4001"

volumes:
  auth_db_data:
